name: Publish site
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'

    - run: npm install

    - run: npm run build
      env:
        CI: true

    - run: touch dist/.nojekyll

    - name: GH Pages publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: 'dist/'
        github_token: ${{ secrets.GITHUB_TOKEN }}
