name: Publish site
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Yarn Install
      with:
        args: yarn install --frozen-lockfile
    - name: Yarn Build
      with:
        args: yarn build
      env:
        CI: true
    - name: GH Pages publish
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: 'build/'
        GH_PAT: ${{ secrets.GH_PAT }}
